import { normalizer } from "@repo/shared/utils";

export const project = {
    url: normalizer.string(process.env.NEXT_PUBLIC_APP_URL, "https://www.treva.realestate"),
    name: normalizer.string(process.env.NEXT_PUBLIC_APP_NAME, "TREVA Real Estate"),
    projectName: "TREVA Real Estate",
    projectDescription: "Azərbaycanda ən böyük daşınmaz əmlak platforması. Developer və brokerləri birləşdirərək, satış və marketinq həlləri təqdim edirik.",
    keywords: ["TREVA Real Estate", "Treva", "daşımaz əmlak", "real estate", "Azerbaijan", "Bakı", "developer", "broker", "satış", "marketinq"],
    defLang: "az",
    staticLanguages: [
        {
            id: 1,
            name: "Azerbaijani",
            native_name: "Azərbaycanca",
            code: "az",
            is_rtl: false,
            is_default_admin: false,
            is_default_site: true,
            is_required: true,
            sort_order: 1,
        },
        {
            id: 2,
            name: "English",
            native_name: "English",
            code: "en",
            is_rtl: false,
            is_default_admin: false,
            is_default_site: false,
            is_required: true,
            sort_order: 2,
        },
        {
            id: 3,
            name: "Russian",
            native_name: "Русский",
            code: "ru",
            is_rtl: false,
            is_default_admin: false,
            is_default_site: false,
            is_required: true,
            sort_order: 3,
        },
    ],
} as const;
