import { normalizer } from "@repo/shared/utils";

export const project = {
    url: normalizer.string(process.env.NEXT_PUBLIC_APP_URL),
    name: normalizer.string(process.env.NEXT_PUBLIC_APP_NAME),
    projectName: "Treva",
    projectDescription: "Treva",
    keywords: ["Treva"],
    defLang: "az",
    staticLanguages: [
        {
            id: 1,
            name: "Azerbaijani",
            native_name: "Azərbaycanca",
            code: "az",
            is_rtl: false,
            is_default_admin: false,
            is_default_site: true,
            is_required: true,
            sort_order: 1,
        },
        {
            id: 2,
            name: "English",
            native_name: "English",
            code: "en",
            is_rtl: false,
            is_default_admin: false,
            is_default_site: false,
            is_required: true,
            sort_order: 2,
        },
        {
            id: 3,
            name: "Russian",
            native_name: "Русский",
            code: "ru",
            is_rtl: false,
            is_default_admin: false,
            is_default_site: false,
            is_required: true,
            sort_order: 3,
        },
    ],
} as const;
